// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygbvlpymkkaatrcgcrad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnYnZscHlta2thYXRyY2djcmFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNDI5ODAsImV4cCI6MjA2MzYxODk4MH0.fH2EMn8bzwYocobs5dkTe9qEcuhjrDViRqolserB_FM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);